name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

env:
  WORKING_DIR: ./starter/backend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.20'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install -d
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run linting
        run: pipenv run lint
        working-directory: ${{ env.WORKING_DIR }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.20'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install -d
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run test
        run: pipenv run test
        working-directory: ${{ env.WORKING_DIR }}

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.WORKING_DIR }}
          tags: mp-backend:latest
          outputs: type=docker,dest=/tmp/mp-backend.tar